export type EditorGroup =
  | "general"
  | "home"
  | "about"
  | "contact"
  | "blog"
  | "listings"
  | "faq"
  | "privacy";
export interface TextFieldDefinition {
  key: string;
  label: string;
  group: EditorGroup;
  multiline: boolean;
}
export const textFields: TextFieldDefinition[] = [
  {
    key: "home_votre_partenaire_a_dubai",
    label: "Votre Partenaire à Dubaï",
    group: "home",
    multiline: false,
  },
  {
    key: "home_immobilier_premium_creation_d_entreprise_residen",
    label: "Immobilier premium · Création d'entreprise · Résidence UAE",
    group: "home",
    multiline: false,
  },
  {
    key: "home_accompagnement_francophone_international_experti",
    label: "Présentation — accompagnement",
    group: "home",
    multiline: false,
  },
  {
    key: "home_explorer_les_opportunites",
    label: "Explorer les opportunités",
    group: "home",
    multiline: false,
  },
  {
    key: "home_consultation_gratuite",
    label: "Consultation gratuite",
    group: "home",
    multiline: false,
  },
  {
    key: "home_clients_accompagnes",
    label: "Clients accompagnés",
    group: "home",
    multiline: false,
  },
  {
    key: "home_rendement_locatif_net",
    label: "Rendement locatif net",
    group: "home",
    multiline: false,
  },
  {
    key: "home_plus_value_moyenne",
    label: "Plus-value moyenne",
    group: "home",
    multiline: false,
  },
  {
    key: "home_impot_sur_le_revenu",
    label: "Impôt sur le revenu",
    group: "home",
    multiline: false,
  },
  {
    key: "home_nos_services",
    label: "Nos Services",
    group: "home",
    multiline: false,
  },
  {
    key: "home_investissement_immobilier_de_haut_rendement_et_c",
    label:
      "Investissement immobilier de haut rendement et création d'entreprise à Dubaï — deux expertises complémentaires pour bâtir votre succès aux Émirats.",
    group: "home",
    multiline: true,
  },
  {
    key: "home_real_estate_investment",
    label: "Real Estate & Investment",
    group: "home",
    multiline: false,
  },
  {
    key: "home_immobilier_premium",
    label: "Immobilier Premium",
    group: "home",
    multiline: false,
  },
  {
    key: "home_accedez_aux_meilleures_opportunites_immobilieres",
    label:
      "Accédez aux meilleures opportunités immobilières à Dubaï : appartements haut rendement, villas de luxe, projets off-plan exclusifs, et Golden Visa.",
    group: "home",
    multiline: true,
  },
  {
    key: "home_rendement_locatif_6_8_net_an",
    label: "Immobilier — rendements indicatifs",
    group: "home",
    multiline: false,
  },
  {
    key: "home_achat_sur_plan_avec_paiement_echelonne",
    label: "Achat sur plan avec paiement échelonné",
    group: "home",
    multiline: false,
  },
  {
    key: "home_golden_visa_eligibility",
    label: "Immobilier — Golden Visa et éligibilité",
    group: "home",
    multiline: false,
  },
  {
    key: "home_gestion_locative_complete",
    label: "Gestion locative complète",
    group: "home",
    multiline: false,
  },
  {
    key: "home_voir_les_biens",
    label: "Voir les biens",
    group: "home",
    multiline: false,
  },
  {
    key: "home_business_setup_relocation",
    label: "Business Setup & Relocation",
    group: "home",
    multiline: false,
  },
  {
    key: "home_installation_complete",
    label: "Installation Complète",
    group: "home",
    multiline: false,
  },
  {
    key: "home_creez_votre_entreprise_a_dubai_et_obtenez_votre_",
    label:
      "Créez votre entreprise à Dubaï et obtenez votre résidence UAE en quelques semaines. Accompagnement complet de A à Z.",
    group: "home",
    multiline: true,
  },
  {
    key: "home_creation_de_societe_freezone_mainland_offshore",
    label: "Création de société (Freezone, Mainland, Offshore)",
    group: "home",
    multiline: false,
  },
  {
    key: "home_visa_de_residence_uae_visas_employes",
    label: "Visa de résidence UAE & visas employés",
    group: "home",
    multiline: false,
  },
  {
    key: "home_ouverture_de_compte_bancaire_corporate",
    label: "Ouverture de compte bancaire corporate",
    group: "home",
    multiline: false,
  },
  {
    key: "home_structuration_fiscale_optimisation",
    label: "Structuration fiscale & optimisation",
    group: "home",
    multiline: false,
  },
  {
    key: "home_demarrer_mon_projet",
    label: "Démarrer mon projet",
    group: "home",
    multiline: false,
  },
  {
    key: "home_pourquoi_movesmart",
    label: "Pourquoi MoveSmart",
    group: "home",
    multiline: false,
  },
  {
    key: "home_accompagnement_multilingue",
    label: "Accompagnement Multilingue",
    group: "home",
    multiline: false,
  },
  {
    key: "home_service_en_francais_anglais_et_arabe_equipe_loca",
    label:
      "Service en français, anglais et arabe. Équipe locale à Dubaï qui comprend vos enjeux.",
    group: "home",
    multiline: true,
  },
  {
    key: "home_transparence_totale",
    label: "Transparence Totale",
    group: "home",
    multiline: false,
  },
  {
    key: "home_aucun_frais_cache_analyse_financiere_rigoureuse_",
    label:
      "Aucun frais caché. Analyse financière rigoureuse. Nous travaillons pour votre ROI.",
    group: "home",
    multiline: false,
  },
  {
    key: "home_expertise_terrain",
    label: "Expertise Terrain",
    group: "home",
    multiline: false,
  },
  {
    key: "home_connaissance_approfondie_du_marche_uae_relations",
    label:
      "Connaissance approfondie du marché UAE. Relations privilégiées avec les développeurs.",
    group: "home",
    multiline: false,
  },
  {
    key: "home_temoignages",
    label: "Témoignages",
    group: "home",
    multiline: false,
  },
  {
    key: "home_passez_a_l_action",
    label: "Passez à l'action",
    group: "home",
    multiline: false,
  },
  {
    key: "home_reservez_votre_consultation_privee_notre_expert_",
    label:
      "Réservez votre consultation privée. Notre expert analyse vos objectifs et vous propose une stratégie sur mesure.",
    group: "home",
    multiline: true,
  },
  {
    key: "home_reserver_un_appel_prive",
    label: "Réserver un appel privé",
    group: "home",
    multiline: false,
  },
  {
    key: "home_whatsapp_direct",
    label: "WhatsApp direct",
    group: "home",
    multiline: false,
  },
  {
    key: "contact_merci",
    label: "Merci!",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_votre_demande_a_ete_envoyee_avec_succes",
    label: "Votre demande a été envoyée avec succès.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_un_conseiller_movesmart_vous_contactera_sous_24h",
    label: "Un conseiller MoveSmart vous contactera sous 24h.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_nouvelle_demande",
    label: "Nouvelle demande",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_contact",
    label: "Contact",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_parlons_de_votre",
    label: "Parlons de votre",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_projet",
    label: "projet.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_que_vous_cherchiez_un_investissement_immobilier_",
    label:
      "Que vous cherchiez un investissement immobilier à fort rendement ou que vous souhaitiez créer votre entreprise à Dubaï, notre équipe d'experts vous accompagne à chaque étape.",
    group: "contact",
    multiline: true,
  },
  {
    key: "contact_disponible_7j_7",
    label: "Disponible 7j/7",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_reponse_sous_24h",
    label: "Réponse sous 24h",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_bureau",
    label: "Bureau",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_rendez_vous_sur_demande",
    label: "Rendez-vous sur demande",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_quel_service_recherchez_vous",
    label: "Quel service recherchez-vous ?",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_selectionnez_une_ou_plusieurs_options",
    label: "Sélectionnez une ou plusieurs options",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_continuer",
    label: "Continuer",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_retour",
    label: "Retour",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_vos_coordonnees",
    label: "Vos coordonnées",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_nom_complet",
    label: "Nom complet",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_john_doe",
    label: "John Doe",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_telephone_whatsapp",
    label: "Téléphone / WhatsApp",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_populaires",
    label: "Populaires",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_tous_les_pays",
    label: "Tous les pays",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_budget_details",
    label: "Budget & Détails",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_budget_estime_objectif_d_investissement_type_de_",
    label: "Budget estimé, objectif d'investissement, type de bien recherché…",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_paiement",
    label: "Paiement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_selectionner",
    label: "Sélectionner…",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_paiement_comptant",
    label: "Paiement comptant",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_plan_de_paiement",
    label: "Plan de paiement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_flexible_a_discuter",
    label: "Flexible / À discuter",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_horizon_d_investissement",
    label: "Horizon d'investissement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_court_terme_1_3_ans",
    label: "Court terme (1-3 ans)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_moyen_terme_3_7_ans",
    label: "Moyen terme (3-7 ans)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_long_terme_7_ans",
    label: "Long terme (7+ ans)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_type_d_activite",
    label: "Type d'activité",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_e_commerce_consulting_trading_etc",
    label: "E-commerce, Consulting, Trading, etc.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_pays_de_residence_actuel",
    label: "Pays de résidence actuel",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_france_algerie_etc",
    label: "France, Algérie, etc.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_nombre_de_visas_souhaites",
    label: "Nombre de visas souhaités",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_type_de_societe",
    label: "Type de société",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_non_decide_besoin_de_conseil",
    label: "Non décidé / Besoin de conseil",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_besoins_bancaires",
    label: "Besoins bancaires",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_compte_professionnel_uniquement",
    label: "Compte professionnel uniquement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_compte_personnel_uniquement",
    label: "Compte personnel uniquement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_les_deux",
    label: "Les deux",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_aucun_besoin_bancaire",
    label: "Aucun besoin bancaire",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_message_additionnel_optionnel",
    label: "Message additionnel (optionnel)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_precisions_questions_contraintes_specifiques",
    label: "Précisions, questions, contraintes spécifiques…",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_un_conseiller_movesmart_vous_contactera_sous_24h_86",
    label: "✓ Un conseiller MoveSmart vous contactera sous 24h",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_envoi_en_cours",
    label: "Envoi en cours…",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_etre_contacte",
    label: "ÊTRE CONTACTÉ",
    group: "contact",
    multiline: false,
  },
  {
    key: "blog_analyses",
    label: "Analyses",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_immobilieres",
    label: "Immobilières.",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_conseils_d_experts_analyses_de_marche_et_guides_",
    label:
      "Conseils d'experts, analyses de marché et guides pour prendre les meilleures décisions d'investissement à Dubaï.",
    group: "blog",
    multiline: true,
  },
  {
    key: "blog_lire_la_suite",
    label: "Lire la suite",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_restez_informe",
    label: "Restez informé",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_abonnez_vous_a_notre_newsletter",
    label: "Abonnez-vous à notre newsletter",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_recevez_les_dernieres_analyses_immobilieres_de_d",
    label:
      "Recevez les dernières analyses immobilières de Dubaï, conseils d'investissement et actualités du marché directement dans votre boîte mail.",
    group: "blog",
    multiline: true,
  },
  {
    key: "blog_votre_adresse_email",
    label: "Votre adresse email",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_s_abonner",
    label: "S'abonner",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_article_non_trouve",
    label: "Article non trouvé",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_retour_au_blog",
    label: "Retour au blog",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_partager",
    label: "Partager",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_articles_similaires",
    label: "Articles similaires",
    group: "blog",
    multiline: false,
  },
  {
    key: "about_page_tag",
    label: "À Propos",
    group: "about",
    multiline: false,
  },
  {
    key: "about_title_1",
    label: "On sécurise",
    group: "about",
    multiline: false,
  },
  {
    key: "about_title_em",
    label: "votre capital.",
    group: "about",
    multiline: false,
  },
  {
    key: "about_p1",
    label:
      "MoveSmart accompagne exclusivement les investisseurs internationaux sur le marché immobilier de Dubaï — off-plan, locatif, revente ou Golden Visa.",
    group: "about",
    multiline: true,
  },
  {
    key: "about_p2",
    label:
      "Notre mission : maximiser votre ROI à chaque étape, de la sélection à la gestion.",
    group: "about",
    multiline: false,
  },
  {
    key: "why_tag",
    label: "Pourquoi Dubaï",
    group: "about",
    multiline: false,
  },
  {
    key: "why_dubai",
    label: "Le marché immobilier de Dubaï",
    group: "about",
    multiline: false,
  },
  {
    key: "why_dubai_em",
    label: "surperforme.",
    group: "about",
    multiline: false,
  },
  {
    key: "hub_title",
    label: "Hub financier mondial",
    group: "about",
    multiline: false,
  },
  {
    key: "hub_desc",
    label: "Centre d'affaires entre Orient et Occident.",
    group: "about",
    multiline: false,
  },
  {
    key: "tax_title",
    label: "Fiscalité — titre",
    group: "about",
    multiline: false,
  },
  {
    key: "tax_desc",
    label: "Fiscalité — précautions",
    group: "about",
    multiline: false,
  },
  {
    key: "biz_title",
    label: "Marché réglementé",
    group: "about",
    multiline: false,
  },
  {
    key: "biz_desc",
    label: "Cadre réglementaire — description",
    group: "about",
    multiline: false,
  },
  {
    key: "growth_title",
    label: "Suivi ROI",
    group: "about",
    multiline: false,
  },
  {
    key: "growth_desc",
    label: "Gestion locative et reporting régulier de votre investissement.",
    group: "about",
    multiline: false,
  },
  {
    key: "approach_tag",
    label: "Notre approche",
    group: "about",
    multiline: false,
  },
  {
    key: "vision_title",
    label: "Analyse de marché",
    group: "about",
    multiline: false,
  },
  {
    key: "vision_desc",
    label: "Sélection rigoureuse basée sur les données de rendement réel.",
    group: "about",
    multiline: false,
  },
  {
    key: "personal_title",
    label: "Négociation exclusive",
    group: "about",
    multiline: false,
  },
  {
    key: "personal_desc",
    label: "Accès aux meilleures offres avant ouverture publique.",
    group: "about",
    multiline: false,
  },
  {
    key: "trust_title",
    label: "Étape — vérification du dossier",
    group: "about",
    multiline: false,
  },
  {
    key: "trust_desc",
    label: "Vérification juridique complète à chaque étape.",
    group: "about",
    multiline: false,
  },
  {
    key: "commit_tag",
    label: "Notre engagement",
    group: "about",
    multiline: false,
  },
  {
    key: "commit_title_1",
    label: "Votre capital",
    group: "about",
    multiline: false,
  },
  {
    key: "commit_title_em",
    label: "notre priorité.",
    group: "about",
    multiline: false,
  },
  {
    key: "commit_p",
    label:
      "Chez MoveSmart, chaque décision est guidée par une seule question : est-ce que cet investissement maximise votre retour tout en minimisant les risques ?",
    group: "about",
    multiline: true,
  },
  {
    key: "commit_cta",
    label: "Prendre rendez-vous",
    group: "about",
    multiline: false,
  },
  {
    key: "listings_page_tag",
    label: "Opportunités",
    group: "listings",
    multiline: false,
  },
  {
    key: "listings_page_title_1",
    label: "Investissements",
    group: "listings",
    multiline: false,
  },
  {
    key: "listings_page_title_em",
    label: "sélectionnés",
    group: "listings",
    multiline: false,
  },
  {
    key: "search_ph",
    label: "Rechercher par projet ou zone...",
    group: "listings",
    multiline: false,
  },
  {
    key: "filters_btn",
    label: "Filtres",
    group: "listings",
    multiline: false,
  },
  {
    key: "filter_min",
    label: "Budget min (AED)",
    group: "listings",
    multiline: false,
  },
  {
    key: "filter_max",
    label: "Budget max (AED)",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_label",
    label: "Trier par",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_recent",
    label: "Récents",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_price_low",
    label: "Prix croissant",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_price_high",
    label: "Prix décroissant",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_beds",
    label: "Chambres",
    group: "listings",
    multiline: false,
  },
  {
    key: "sort_area",
    label: "Surface",
    group: "listings",
    multiline: false,
  },
  {
    key: "no_listings",
    label: "Aucune opportunité disponible pour le moment.",
    group: "listings",
    multiline: false,
  },
  {
    key: "no_results",
    label: "Aucun résultat.",
    group: "listings",
    multiline: false,
  },
  {
    key: "listings_no_img",
    label: "Aucune photo",
    group: "listings",
    multiline: false,
  },
  {
    key: "sqft_label",
    label: "sqft",
    group: "listings",
    multiline: false,
  },
  {
    key: "not_found",
    label: "Bien non trouvé.",
    group: "listings",
    multiline: false,
  },
  {
    key: "back",
    label: "Retour",
    group: "listings",
    multiline: false,
  },
  {
    key: "copied",
    label: "Copié ✓",
    group: "listings",
    multiline: false,
  },
  {
    key: "share",
    label: "Partager",
    group: "listings",
    multiline: false,
  },
  {
    key: "beds_label",
    label: "Chambres",
    group: "listings",
    multiline: false,
  },
  {
    key: "baths_label",
    label: "SDB",
    group: "listings",
    multiline: false,
  },
  {
    key: "desc_label",
    label: "Détails du bien",
    group: "listings",
    multiline: false,
  },
  {
    key: "price_label",
    label: "Prix d'acquisition",
    group: "listings",
    multiline: false,
  },
  {
    key: "msg_btn",
    label: "Envoyer une demande",
    group: "listings",
    multiline: false,
  },
  {
    key: "wa_btn",
    label: "Contacter sur WhatsApp",
    group: "listings",
    multiline: false,
  },
  {
    key: "team_note",
    label: "Réponse sous 2h. Accompagnement investisseur complet.",
    group: "listings",
    multiline: false,
  },
  {
    key: "contact_option_real_estate",
    label: "Immobilier & Investissement",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_rental_income",
    label: "Revenus locatifs",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_capital_appreciation",
    label: "Appréciation du capital",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_flip",
    label: "Achat & Revente (Flip)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_primary_residence",
    label: "Résidence principale",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_golden_visa",
    label: "Golden Visa via l'immobilier",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_off_plan",
    label: "Investissement sur plan",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_business_setup",
    label: "Création d'entreprise & Relocalisation",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_company_formation",
    label: "Création d'entreprise",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_uae_residency",
    label: "Visa de résidence EAU",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_bank_account",
    label: "Ouverture de compte bancaire",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_tax_optimization",
    label: "Optimisation fiscale",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_option_full_setup",
    label: "Installation complète aux EAU",
    group: "contact",
    multiline: false,
  },
  {
    key: "home_hero_title",
    label: "Bannière — titre principal",
    group: "home",
    multiline: false,
  },
  {
    key: "home_hero_connector",
    label: "Bannière — liaison (ex. &)",
    group: "home",
    multiline: false,
  },
  {
    key: "home_hero_accent",
    label: "Bannière — texte en doré",
    group: "home",
    multiline: false,
  },
  {
    key: "home_services_title",
    label: "Services — titre",
    group: "home",
    multiline: false,
  },
  {
    key: "home_services_accent",
    label: "Services — titre en doré",
    group: "home",
    multiline: false,
  },
  {
    key: "home_why_title",
    label: "Pourquoi nous — titre",
    group: "home",
    multiline: false,
  },
  {
    key: "home_why_accent",
    label: "Pourquoi nous — titre en doré",
    group: "home",
    multiline: false,
  },
  {
    key: "home_testimonials_title",
    label: "Témoignages — titre",
    group: "home",
    multiline: false,
  },
  {
    key: "home_testimonials_accent",
    label: "Témoignages — titre en doré",
    group: "home",
    multiline: false,
  },
  {
    key: "home_cta_title",
    label: "Appel à l’action — titre",
    group: "home",
    multiline: false,
  },
  {
    key: "home_cta_accent",
    label: "Appel à l’action — texte en doré",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_1_value",
    label: "Statistique 1 — valeur",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_2_value",
    label: "Statistique 2 — valeur",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_3_value",
    label: "Statistique 3 — valeur",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_4_value",
    label: "Statistique 4 — valeur",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_3_label",
    label: "Statistique 3 — libellé",
    group: "home",
    multiline: false,
  },
  {
    key: "home_stat_4_label",
    label: "Statistique 4 — libellé",
    group: "home",
    multiline: false,
  },
  {
    key: "about_approach_title",
    label: "L’investissement",
    group: "about",
    multiline: false,
  },
  {
    key: "about_approach_accent",
    label: "clé en main.",
    group: "about",
    multiline: false,
  },
  {
    key: "about_step",
    label: "Étape",
    group: "about",
    multiline: false,
  },
  {
    key: "about_discuss",
    label: "Discuter d’un projet",
    group: "about",
    multiline: false,
  },
  {
    key: "listings_count_one",
    label: "{{count}} opportunité",
    group: "listings",
    multiline: false,
  },
  {
    key: "listings_count_other",
    label: "{{count}} opportunités",
    group: "listings",
    multiline: false,
  },
  {
    key: "gallery_previous",
    label: "Photo précédente",
    group: "listings",
    multiline: false,
  },
  {
    key: "gallery_next",
    label: "Photo suivante",
    group: "listings",
    multiline: false,
  },
  {
    key: "gallery_photo",
    label: "Photo {{number}}",
    group: "listings",
    multiline: false,
  },
  {
    key: "loading",
    label: "Chargement…",
    group: "general",
    multiline: false,
  },
  {
    key: "retry",
    label: "Réessayer",
    group: "general",
    multiline: false,
  },
  {
    key: "data_error",
    label: "Impossible de charger les données. Veuillez réessayer.",
    group: "general",
    multiline: false,
  },
  {
    key: "share_error",
    label: "Partage indisponible. Copiez le lien de cette page.",
    group: "general",
    multiline: false,
  },
  {
    key: "theme_light",
    label: "Mode clair",
    group: "general",
    multiline: false,
  },
  {
    key: "theme_dark",
    label: "Mode sombre",
    group: "general",
    multiline: false,
  },
  {
    key: "menu_open",
    label: "Ouvrir le menu",
    group: "general",
    multiline: false,
  },
  {
    key: "menu_close",
    label: "Fermer le menu",
    group: "general",
    multiline: false,
  },
  {
    key: "language_select",
    label: "Choisir la langue",
    group: "general",
    multiline: false,
  },
  {
    key: "blog",
    label: "Journal",
    group: "general",
    multiline: false,
  },
  {
    key: "footer_tagline",
    label: "Investir et s’installer à Dubaï, en toute clarté.",
    group: "general",
    multiline: false,
  },
  {
    key: "footer_rights",
    label: "Tous droits réservés.",
    group: "general",
    multiline: false,
  },
  {
    key: "privacy_link",
    label: "Confidentialité",
    group: "general",
    multiline: false,
  },
  {
    key: "privacy_title",
    label: "Politique de confidentialité",
    group: "privacy",
    multiline: false,
  },
  {
    key: "privacy_content",
    label: "Politique de confidentialité — contenu",
    group: "privacy",
    multiline: true,
  },
  {
    key: "contact_consent",
    label:
      "J’accepte que mes coordonnées soient utilisées pour répondre à ma demande.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_submit_error",
    label:
      "Votre demande n’a pas été envoyée. Réessayez ou contactez-nous par WhatsApp / email.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_validation_error",
    label: "Vérifiez votre nom, email, téléphone et votre accord.",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_email",
    label: "Email",
    group: "contact",
    multiline: false,
  },
  {
    key: "newsletter_consent",
    label: "J’accepte de recevoir la newsletter. Désinscription sur demande.",
    group: "blog",
    multiline: false,
  },
  {
    key: "newsletter_success",
    label: "Votre inscription a bien été enregistrée.",
    group: "blog",
    multiline: false,
  },
  {
    key: "newsletter_error",
    label: "Inscription non enregistrée. Veuillez réessayer.",
    group: "blog",
    multiline: false,
  },
  {
    key: "newsletter_sending",
    label: "Inscription…",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_tag",
    label: "Journal",
    group: "blog",
    multiline: false,
  },
  {
    key: "blog_empty",
    label: "De nouveaux articles arrivent bientôt.",
    group: "blog",
    multiline: false,
  },
  {
    key: "wa_status",
    label: "Parlons de votre projet",
    group: "general",
    multiline: false,
  },
  {
    key: "wa_text",
    label:
      "Besoin d’aide pour votre projet à Dubaï ? Discutez directement avec notre équipe.",
    group: "general",
    multiline: false,
  },
  {
    key: "wa_button",
    label: "Démarrer la discussion",
    group: "general",
    multiline: false,
  },
  {
    key: "wa_message",
    label:
      "Bonjour, je souhaite obtenir des informations sur vos services à Dubaï.",
    group: "general",
    multiline: false,
  },
  {
    key: "not_found_title",
    label: "Page introuvable",
    group: "general",
    multiline: false,
  },
  {
    key: "not_found_text",
    label: "Cette page n’existe pas ou a été déplacée.",
    group: "general",
    multiline: false,
  },
  {
    key: "back_home",
    label: "Retour à l’accueil",
    group: "general",
    multiline: false,
  },
  {
    key: "property_interest",
    label: "Bonjour, je suis intéressé par le bien : {{title}}. {{url}}",
    group: "listings",
    multiline: false,
  },
  {
    key: "property_description_fallback",
    label:
      "Contactez notre équipe pour obtenir les informations détaillées sur ce bien.",
    group: "listings",
    multiline: false,
  },
  {
    key: "investment_disclaimer",
    label:
      "Les rendements présentés sont indicatifs, non garantis et soumis aux conditions du marché.",
    group: "home",
    multiline: true,
  },
  {
    key: "faq_tag",
    label: "FAQ",
    group: "faq",
    multiline: false,
  },
  {
    key: "faq_title",
    label: "Vos questions.",
    group: "faq",
    multiline: false,
  },
  {
    key: "faq_accent",
    label: "Nos réponses claires.",
    group: "faq",
    multiline: false,
  },
  {
    key: "seo_home_title",
    label: "Référencement — titre de la page",
    group: "home",
    multiline: false,
  },
  {
    key: "seo_home_description",
    label: "Référencement — description de la page",
    group: "home",
    multiline: true,
  },
  {
    key: "seo_about_title",
    label: "Référencement — titre de la page",
    group: "about",
    multiline: false,
  },
  {
    key: "seo_about_description",
    label: "Référencement — description de la page",
    group: "about",
    multiline: true,
  },
  {
    key: "seo_listings_title",
    label: "Référencement — titre de la page",
    group: "listings",
    multiline: false,
  },
  {
    key: "seo_listings_description",
    label: "Référencement — description de la page",
    group: "listings",
    multiline: true,
  },
  {
    key: "seo_contact_title",
    label: "Référencement — titre de la page",
    group: "contact",
    multiline: false,
  },
  {
    key: "seo_contact_description",
    label: "Référencement — description de la page",
    group: "contact",
    multiline: true,
  },
  {
    key: "seo_blog_title",
    label: "Référencement — titre de la page",
    group: "blog",
    multiline: false,
  },
  {
    key: "seo_blog_description",
    label: "Référencement — description de la page",
    group: "blog",
    multiline: true,
  },
  {
    key: "seo_privacy_title",
    label: "Référencement — titre de la page",
    group: "privacy",
    multiline: false,
  },
  {
    key: "seo_privacy_description",
    label: "Référencement — description de la page",
    group: "privacy",
    multiline: true,
  },
  {
    key: "preview_forms_disabled",
    label: "Formulaire désactivé dans l’aperçu du brouillon.",
    group: "general",
    multiline: false,
  },
  {
    key: "about_followup_title",
    label: "Suivi de votre investissement",
    group: "about",
    multiline: false,
  },
  {
    key: "about_followup_desc",
    label: "Accompagnement après acquisition et suivi de votre projet.",
    group: "about",
    multiline: false,
  },
  {
    key: "contact_freezone",
    label: "Zone franche (Freezone)",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_mainland",
    label: "Mainland",
    group: "contact",
    multiline: false,
  },
  {
    key: "contact_offshore",
    label: "Offshore",
    group: "contact",
    multiline: false,
  },
  {
    key: "home",
    label: "Navigation — Accueil",
    group: "general",
    multiline: false,
  },
  {
    key: "listings",
    label: "Navigation — Biens",
    group: "general",
    multiline: false,
  },
  {
    key: "about",
    label: "Navigation — À propos",
    group: "general",
    multiline: false,
  },
  {
    key: "contact",
    label: "Navigation — Contact",
    group: "general",
    multiline: false,
  },
  {
    key: "listings_load_more",
    label: "Bouton — afficher plus de biens ({{shown}} / {{total}})",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_apartment",
    label: "Type de bien — Appartement",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_villa",
    label: "Type de bien — Villa",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_penthouse",
    label: "Type de bien — Penthouse",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_house",
    label: "Type de bien — Maison",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_townhouse",
    label: "Type de bien — Maison de ville",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_studio",
    label: "Type de bien — Studio",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_office",
    label: "Type de bien — Bureau",
    group: "listings",
    multiline: false,
  },
  {
    key: "listing_type_land",
    label: "Type de bien — Terrain",
    group: "listings",
    multiline: false,
  },
];
